# Project Identification
sonar.projectKey=notes-app-mern
sonar.projectName=Notes App (Frontend & Backend)
sonar.projectVersion=1.0.0

# Source Code and Test Directories
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=frontend/src/**/__tests__/**,backend/tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,.scannerwork/**,frontend/src/test/**,frontend/src/**/__tests__/**

# TypeScript Compiler Configurations
sonar.typescript.tsconfigPaths=frontend/tsconfig.json,backend/tsconfig.json

# Code Coverage Configurations (Frontend Jest & Backend c8)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
